13 тз первая выгрузка
AleksandrGimanov/java-shareit pull request #1
Opened 2023-05-03 12:58 UTC by AleksandrGimanov

2023-05-03 19:45 UTC, z8q requested changes

2023-05-03 19:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserDto createUser(@Valid @RequestBody UserDto userDto) {
При попытке сохранения дубля приходит:
{
	"timestamp": "2023-05-03T18:16:01.525+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/users/"
}

Хотя в логах выходит понятная ошибка:
`Пользователь с таким адресом Эл. почты user@yandex.ru уже существует!`
Можно было бы возвращать такое описание в ответном объекте

2023-05-03 19:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +        if (id != 0 && !users.containsKey(id)) {
Вот тут интересно.
Делаю `PATCH http://localhost:8080/users/0`
{
	"name": "Bob",
	"email": "bob@yandex.ru"
}
И падаю в 46-й строке с nullPointerException.
Почему проверяем id != 0?

На `DELETE http://localhost:8080/users/0` приходит ответ 200
Пишет `Пользователь с  id: 0 удален`

2023-05-03 19:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        getUserById(user.getId());
Тут и в 36-й не совсем понимаю вызов getUserById.
Если для проверки наличия, то в storage тоже ведь выполняется checkId()

2023-05-03 19:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +    private final Map<Long, List<Item>> userItemIndex = new LinkedHashMap<>();
Почему решили использовать LinkedHashMap?

2023-05-03 20:27 UTC, AleksandrGimanov commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +    private final Map<Long, List<Item>> userItemIndex = new LinkedHashMap<>();
На самом деле просто так, на одном из форумов наткнулся на пример с использованием computeifabsent и там при сравнении ключей была рекомендация использовать LinkedHashMap. Да и логичнее чтобы список предметов user был в одном виде, по мере добавления item , а не рандомным видом каждый раз

2023-05-03 20:33 UTC, AleksandrGimanov commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +    private final Map<Long, List<Item>> userItemIndex = new LinkedHashMap<>();
![image](https://user-images.githubusercontent.com/113610062/236043223-53c70b64-4e61-4c59-a279-fef69969c8f4.png)

2023-05-03 20:38 UTC, AleksandrGimanov commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        getUserById(user.getId());
переборщил с проверками, удалил в методе  Delete , Update

2023-05-03 20:51 UTC, AleksandrGimanov commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserDto createUser(@Valid @RequestBody UserDto userDto) {
Переделал на ошибку 409

2023-05-03 20:58 UTC, AleksandrGimanov commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        getUserById(user.getId());
Так же поправил методы в ItemService

2023-05-04 19:46 UTC, z8q approved these changes

2023-05-07 09:18 UTC, merged