14 тз Первая выгрузка
AleksandrGimanov/java-shareit pull request #2
Opened 2023-05-26 04:41 UTC by AleksandrGimanov

2023-05-27 05:06 UTC, z8q requested changes

2023-05-27 05:06 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      public List<ItemDto> getItemsByText(@RequestHeader("X-Sharer-User-Id") long userId,
Похоже, что тут и в deleteItem не используем userId.
А без этого хэдера запрос не проходит

2023-05-27 05:06 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public Booking createBooking(@RequestHeader("X-Sharer-User-Id") long userId,
Когда задаем прошедшее время бронирования, приходит ошибка. Это хорошо.
Но стоит еще добавить описание причины ошибки.
Сейчас приходит:
{
	"timestamp": "2023-05-27T04:35:46.343+00:00",
	"status": 400,
	"error": "Bad Request",
	"path": "/bookings"
}

2023-05-27 05:06 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      @GetMapping
Из ТЗ:
`Теперь нужно, чтобы владелец видел даты последнего и ближайшего следующего бронирования для каждой вещи, когда просматривает список (GET /items).`
По запросу приходит следующее:
{
		"id": 1,
		"name": "car",
		"description": "Tesla",
		"available": true,
		"owner": 1,
		"lastBooking": {
			"id": 1,
			"bookerId": 2  `нужно добавить даты`
		},
		"nextBooking": {
			"id": 4,
			"bookerId": 3
		}
},

2023-05-27 05:06 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public CommentDto createComment(@RequestHeader("X-Sharer-User-Id") long userId,
Из ТЗ:
`Отзывы можно будет увидеть по двум эндпоинтам — по GET /items/{itemId} для одной конкретной вещи и по GET /items для всех вещей данного пользователя. `
По `GET /items/{itemId}` все хорошо, отзывы. отображаются.
По вызову `GET /items` отзывы не видны

2023-05-27 05:06 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                 @Valid @RequestBody BookingDto bookingDto) {
В качестве входных аргументов используем Dto.
Для возвращаемых значений нужно тоже использовать Dto.
Сейчас происходит возврат объектов Entity классов.
Это нужно по всем контроллерам посмотреть

2023-05-27 06:11 UTC, AleksandrGimanov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      public List<ItemDto> getItemsByText(@RequestHeader("X-Sharer-User-Id") long userId,
В обоих случаях, просто убрал этот параметр, так как не используется

2023-05-27 06:34 UTC, AleksandrGimanov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public Booking createBooking(@RequestHeader("X-Sharer-User-Id") long userId,
добавил MethodArgumentNotValidException в  отлов

2023-05-27 11:08 UTC, AleksandrGimanov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public CommentDto createComment(@RequestHeader("X-Sharer-User-Id") long userId,
Добавил

2023-05-27 11:09 UTC, AleksandrGimanov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      @GetMapping
Даты добавил

2023-05-28 04:06 UTC, AleksandrGimanov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                 @Valid @RequestBody BookingDto bookingDto) {
Исправил

2023-05-28 20:25 UTC, z8q approved these changes

2023-07-03 13:54 UTC, merged